apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: BACKEND_IMAGE_URI
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO

            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_JPA_SHOW_SQL

            - name: SPRING_H2_CONSOLE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_H2_CONSOLE_ENABLED

            - name: SERVER_SERVLET_CONTEXT_PATH
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SERVER_SERVLET_CONTEXT_PATH

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: SPRING_DATASOURCE_PASSWORD

          readinessProbe:
            httpGet:
              path: /api/books
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/books
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 20
            failureThreshold: 3